# Generated by Django 6.0.6 on 2026-07-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('entreprise', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('qualifie', 'Qualifié'), ('perdu', 'Perdu')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du rendez-vous')),
                ('heure', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('email_confirmation_envoye', models.BooleanField(default=False, verbose_name='Email de confirmation envoyé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='rdv.prospect')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date', 'heure'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut__in', ['en_attente', 'confirme'])), fields=('date', 'heure'), name='creneau_unique_actif')],
            },
        ),
    ]
