# Generated by Django 5.2.15 on 2026-07-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('developpement', 'Développement'), ('design', 'Design / UI-UX'), ('infrastructure', 'Infrastructure / DevOps'), ('formation', 'Formation / Accompagnement'), ('maintenance', 'Maintenance / Support'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('prix_reference', models.DecimalField(decimal_places=2, help_text='Prix de référence en TND', max_digits=10)),
                ('actif', models.BooleanField(default=True, help_text="Décoche pour retirer du catalogue sans supprimer l'historique")),
            ],
            options={
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='devis.prestation'),
        ),
    ]
