# Generated by Django 5.2.15 on 2026-08-02 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devis', '0002_prestation_lignedevis_prestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('type_rdv', models.CharField(choices=[('appel', 'Appel téléphonique'), ('visio', 'Visioconférence'), ('sur_site', 'Sur site')], default='appel', max_length=20)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='demande', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Objet de l'appel / sujet à aborder")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='devis.client')),
                ('devis', models.ForeignKey(blank=True, help_text='Devis concerné par ce rendez-vous (facultatif)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='devis.devis')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous (Ligne directe)',
                'ordering': ['-date_rdv', '-heure_rdv'],
            },
        ),
    ]
